name: Legacy Tests

on:
  push:
    branches:
      - "develop"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Test with pytest
        timeout-minutes: 5
        run: |
          uv run pytest \
            -n auto \
            --cov src \
            --splits 8 --group ${{ matrix.group }} \
            --timeout 15 \
            -o junit_suite_name="${{github.job}}-${{ matrix.group }}" \
            tests/unit

      - uses: ./.github/actions/report
        with:
          flag: unit-tests
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  parse-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Cache oss-repos
        uses: ./.github/actions/setup-oss-repos

      - name: Install yarn and pnpm
        run: |
          npm install -g yarn &
          npm install -g pnpm

      - name: Test with pytest
        timeout-minutes: 15
        env:
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE
        run: |
          uv run pytest \
            -n auto \
            -o junit_suite_name="${{github.job}}" \
            tests/integration/codemod/test_parse.py

      - uses: ./.github/actions/report
        with:
          flag: no-flag
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Test with pytest
        timeout-minutes: 5
        env:
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE
          GITHUB_TOKEN: ${{ secrets.GHA_PAT }}
        run: |
          uv run pytest \
            -n auto \
            -o junit_suite_name="${{github.job}}" \
            tests/integration/codegen

      - uses: ./.github/actions/report
        with:
          flag: integration-tests
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
